# Generated by Django 3.1.7 on 2021-04-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210401_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='t', max_length=50),
            preserve_default=False,
        ),
    ]
