# Generated by Django 3.1.7 on 2021-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_comment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Hold down “Control”, or “Command” on a Mac, to select more than one.', to='post.Category'),
        ),
    ]
